#!/bin/bash

# : ${DOCKER_USER:? required}
image=wangweicoding-docker.pkg.coding.net/cd-production/cd/admission-webhook:v12
~/go/bin/dep ensure -v
CGO_ENABLED=0 GOOS=linux go build -a -installsuffix cgo -o admission-webhook-example 
docker build --no-cache -t ${image} .
rm -rf admission-webhook-example

docker push ${image}