apiVersion: admissionregistration.k8s.io/v1beta1
kind: ValidatingWebhookConfiguration
metadata:
  name: validation-webhook-example-cfg
  labels:
    app: admission-webhook-example
webhooks:
  - name: required-labels
    clientConfig:
      service:
        name: admission-webhook-example-svc
        namespace: default
        path: "/validate"
      caBundle: LS0tLS1CRUdJTiBDRVJUSUZJQ0FURS0tLS0tCk1JSUN5RENDQWJDZ0F3SUJBZ0lCQURBTkJna3Foa2lHOXcwQkFRc0ZBREFWTVJNd0VRWURWUVFERXdwcmRXSmwKY201bGRHVnpNQjRYRFRJd01EUXhOekEzTURNek1sb1hEVE13TURReE5UQTNNRE16TWxvd0ZURVRNQkVHQTFVRQpBeE1LYTNWaVpYSnVaWFJsY3pDQ0FTSXdEUVlKS29aSWh2Y05BUUVCQlFBRGdnRVBBRENDQVFvQ2dnRUJBSnlaCjQvRG9MWEswdkNEUENsZ1gzZmVCaDNnb3NoZ0xVZ2FZRjhrV0ZjZU5TRWMwem55RnBleElSR0hnWG1BTjBSK1gKY3gwUnFMNktaNDlpd2VXejlXTVNaTXVmdW9qbVMwNXJuSG56Wk5TaVdlMS9oTnpNa0NXZWlWWmZwVSs5cHhoZQpML1JlYUtyMmJ0SS9vZE5PSm9BM3ZlV3ZzeHJkdVRwTUUzKzdYSnk4eVRXN0FhbHJjQWZBSGl4Z2FUSDJ3ZWt1CnRPbTQzaGhVNXRnMHZQRVNPK1lVTjhpU1R3K1pyUUlMaVdqKzYwaXJ4MENVc2tzemF5eklpY0J3UVB3T0p2RTQKbENWMEtaOXNmdUdmMENKTUF2b0hhY1g0eXg2U3BKZVBKSldnNGNGREY3WTk5QmRYZkwwZ3dmaU8xd2NJdlRyVwpRM0RLRmhaQ3dKRWNacmVuMzJNQ0F3RUFBYU1qTUNFd0RnWURWUjBQQVFIL0JBUURBZ0tVTUE4R0ExVWRFd0VCCi93UUZNQU1CQWY4d0RRWUpLb1pJaHZjTkFRRUxCUUFEZ2dFQkFCSlFpMFpyMjczOTRtU2VoZzlaWTNnSEU4ZjEKbHVBVExDSTMrcnA5Y2cwZzZ6T2dENEdSak5ObXd2WUcvRXFiS0JnQUlEMnVEQjhwNWFNT1FMSUJhT0Z0Nk1VRgpPdy8zOU0yL0xoYTlhUWJ6U0xmUjd0LzJ5cFhMUFVubmlqcklIdTloSmUzcjlXa09Ccnd1bVhzVmxWUFB5K2F0CmNGR25iS2xTNVJ3SFcvcCtoYnp3c3ZHd0tBajJhUTNaYmNkK1pYVFlLNEFOVmRIWkRHS2RKa0lhb0JMaFlZeVYKTDlpdXVzdDNzRDA3ajYvRk1DZUorTjFWUndJMVdyZHp4aDJnZ04zWGRwWm9GSDRKeWovUzU0YnZwZUsyMGpLWgpBZEV1TVAyazJGY0w3UEJFdU1RMW9PVGpmd0xTeW5YN1pxRU5aL3Q2WHhsdkRlOE5ReXVZeTU0NGlycz0KLS0tLS1FTkQgQ0VSVElGSUNBVEUtLS0tLQo=
    rules:
      - operations: [ "CREATE" ]
        apiGroups: ["apps", ""]
        apiVersions: ["v1"]
        resources: ["deployments","services"]
    namespaceSelector:
      matchLabels:
        admission-webhook-example: enabled
